[package]
name = "webby-s"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
log = "0.4.25"
simple_logger = "5.0.0"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
